# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plea', '0037_auto_20170614_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='event_subtype',
            field=models.CharField(choices=[('not_set', 'Not set'), ('success', 'Success'), ('EXT1', 'External failure 1'), ('EXT2', 'External failure 2'), ('case_strict_validation_failed', 'Form Validation Error: Strict'), ('case_loose_validation_failed', 'Form Validation Error: Loose'), ('case_invalid_missing_name', 'Invalid Case: Missing Name'), ('case_invalid_missing_urn', 'Invalid Case: Missing URN'), ('case_invalid_invalid_urn', 'Invalid Case: Invalid URN'), ('case_invalid_missing_dateofhearing', 'Invalid Case: Missing date of hearing'), ('case_invalid_name_too_long', 'Invalid Case: Name too long'), ('case_invalid_offencecode', 'Invalid Case: Invalid offence code'), ('case_invalid_courtcode', 'Invalid Case: Invalid court code'), ('case_invalid_not_in_whitelist', 'Invalid Case: Not in whitelist'), ('case_invalid_duplicate_offence', 'Invalid Case: Duplicate offence'), ('case_invalid_duplicate_urn_used', 'Invalid Case: Duplicate URN already used (sent)'), ('case_invalid_no_offences', 'Invalid Case: No offences'), ('result_invalid_duplicate_urn_used', 'Invalid Result: Duplicate URN already used (sent)'), ('case_invalid_invalid_date', 'Invalid Case: Invalid date field')], help_text='The specific reason for the event', max_length=255, verbose_name='reason for failure'),
        ),
    ]
