# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plea', '0037_auto_20170614_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='event_subtype',
            field=models.CharField(choices=[(b'not_set', b'Not set'), (b'success', b'Success'), (b'EXT1', b'External failure 1'), (b'EXT2', b'External failure 2'), (b'case_strict_validation_failed', b'Form Validation Error: Strict'), (b'case_loose_validation_failed', b'Form Validation Error: Loose'), (b'case_invalid_missing_name', b'Invalid Case: Missing Name'), (b'case_invalid_missing_urn', b'Invalid Case: Missing URN'), (b'case_invalid_invalid_urn', b'Invalid Case: Invalid URN'), (b'case_invalid_missing_dateofhearing', b'Invalid Case: Missing date of hearing'), (b'case_invalid_name_too_long', b'Invalid Case: Name too long'), (b'case_invalid_offencecode', b'Invalid Case: Invalid offence code'), (b'case_invalid_courtcode', b'Invalid Case: Invalid court code'), (b'case_invalid_not_in_whitelist', b'Invalid Case: Not in whitelist'), (b'case_invalid_duplicate_offence', b'Invalid Case: Duplicate offence'), (b'case_invalid_duplicate_urn_used', b'Invalid Case: Duplicate URN already used (sent)'), (b'case_invalid_no_offences', b'Invalid Case: No offences'), (b'result_invalid_duplicate_urn_used', b'Invalid Result: Duplicate URN already used (sent)'), (b'case_invalid_invalid_date', b'Invalid Case: Invalid date field')], help_text=b'The specific reason for the event', max_length=255, verbose_name=b'reason for failure'),
        ),
    ]
